export const LOGIN_SELLER_REQUEST = "LOGIN_SELLER_REQUEST";
export const LOGIN_SELLER_SUCCESS = "LOGIN_SELLER_SUCCESS";
export const LOGIN_SELLER_FAIL = "LOGIN_SELLER_FAIL";

export const REGISTER_SELLER_REQUEST = "REGISTER_SELLER_REQUEST";
export const REGISTER_SELLER_SUCCESS = "REGISTER_SELLER_SUCCESS";
export const REGISTER_SELLER_FAIL = "REGISTER_SELLER_FAIL";

export const LOAD_SELLER_REQUEST = "LOAD_SELLER_REQUEST";
export const LOAD_SELLER_SUCCESS = "LOAD_SELLER_SUCCESS";
export const LOAD_SELLER_FAIL = "LOAD_SELLER_FAIL";

export const LOGOUT_SELLER_SUCCESS = "LOGOUT_SELLER_SUCCESS";
export const LOGOUT_SELLER_FAIL = "LOGOUT_SELLER_FAIL";


export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";

export const SELLER_STATS_REQUEST = "SELLER_STATS_REQUEST";
export const SELLER_STATS_SUCCESS = "SELLER_STATS_SUCCESS";
export const SELLER_STATS_FAIL = "SELLER_STATS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
